name: Deploy to EC2

on:
  push:
    branches: [  master ]  # Adjust based on your branch name

jobs:
  deploy:
    runs-on: self-hosted


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ECHOMATELITE/echo-mate-lite-main
            git pull origin main

            cd backend
            npm install --production

            cd ../frontend/twitterclone
            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            pm2 restart echomatelite-backend || pm2 start index.js --name echomatelite-backend
            sudo systemctl reload apache2
