name: Deploy on EC2 Runner

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: |
          cd ~/ECHOMATELITE/echo-mate-lite-main/backend
          npm install --production

      - name: Install frontend dependencies and build
        run: |
          cd ~/ECHOMATELITE/echo-mate-lite-main/frontend/twitterclone
          npm install
          npm run build

      - name: Clean old build and deploy frontend
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ~/ECHOMATELITE/echo-mate-lite-main/frontend/twitterclone/build/* /var/www/html/

      - name: Restart backend
        run: |
          pm2 restart echomatelite-backend || pm2 start ~/ECHOMATELITE/echo-mate-lite-main/backend/index.js --name echomatelite-backend

      - name: Reload Apache
        run: sudo systemctl reload apache2
